//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.24 at 01:37:45 PM IST 
//

package com.photon.phresco.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drupalEshopData" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firstnamevalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastnamevalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="companyvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="streetaddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="streetaddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cityvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="countryvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="statevalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="postelcodecvalue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ordercommvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "drupalEshopData" })
@XmlRootElement(name = "drupalEshops")
public class DrupalEshops {

	protected List<DrupalEshops.DrupalEshopData> drupalEshopData;

	/**
	 * Gets the value of the drupalEshopData property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the drupalEshopData property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDrupalEshopData().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DrupalEshops.DrupalEshopData }
	 * 
	 * 
	 */
	public List<DrupalEshops.DrupalEshopData> getDrupalEshopData() {
		if (drupalEshopData == null) {
			drupalEshopData = new ArrayList<DrupalEshops.DrupalEshopData>();
		}
		return this.drupalEshopData;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="firstnamevalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="lastnamevalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="companyvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="streetaddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="streetaddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cityvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="countryvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="statevalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="postelcodecvalue" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="ordercommvalue" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "firstnamevalue", "lastnamevalue",
			"companyvalue", "streetaddress1", "streetaddress2", "cityvalue",
			"countryvalue", "statevalue", "postelcodecvalue", "ordercommvalue" })
	public static class DrupalEshopData {

		@XmlElement(required = true)
		protected String firstnamevalue;
		@XmlElement(required = true)
		protected String lastnamevalue;
		@XmlElement(required = true)
		protected String companyvalue;
		@XmlElement(required = true)
		protected String streetaddress1;
		@XmlElement(required = true)
		protected String streetaddress2;
		@XmlElement(required = true)
		protected String cityvalue;
		@XmlElement(required = true)
		protected String countryvalue;
		@XmlElement(required = true)
		protected String statevalue;
		protected String postelcodecvalue;
		@XmlElement(required = true)
		protected String ordercommvalue;

		/**
		 * Gets the value of the firstnamevalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFirstnamevalue() {
			return firstnamevalue;
		}

		/**
		 * Sets the value of the firstnamevalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFirstnamevalue(String value) {
			this.firstnamevalue = value;
		}

		/**
		 * Gets the value of the lastnamevalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getLastnamevalue() {
			return lastnamevalue;
		}

		/**
		 * Sets the value of the lastnamevalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setLastnamevalue(String value) {
			this.lastnamevalue = value;
		}

		/**
		 * Gets the value of the companyvalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCompanyvalue() {
			return companyvalue;
		}

		/**
		 * Sets the value of the companyvalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCompanyvalue(String value) {
			this.companyvalue = value;
		}

		/**
		 * Gets the value of the streetaddress1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getStreetaddress1() {
			return streetaddress1;
		}

		/**
		 * Sets the value of the streetaddress1 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setStreetaddress1(String value) {
			this.streetaddress1 = value;
		}

		/**
		 * Gets the value of the streetaddress2 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getStreetaddress2() {
			return streetaddress2;
		}

		/**
		 * Sets the value of the streetaddress2 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setStreetaddress2(String value) {
			this.streetaddress2 = value;
		}

		/**
		 * Gets the value of the cityvalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCityvalue() {
			return cityvalue;
		}

		/**
		 * Sets the value of the cityvalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCityvalue(String value) {
			this.cityvalue = value;
		}

		/**
		 * Gets the value of the countryvalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCountryvalue() {
			return countryvalue;
		}

		/**
		 * Sets the value of the countryvalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCountryvalue(String value) {
			this.countryvalue = value;
		}

		/**
		 * Gets the value of the statevalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getStatevalue() {
			return statevalue;
		}

		/**
		 * Sets the value of the statevalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setStatevalue(String value) {
			this.statevalue = value;
		}

		/**
		 * Gets the value of the postelcodecvalue property.
		 * 
		 */
		public String getPostelcodecvalue() {
			return postelcodecvalue;
		}

		/**
		 * Sets the value of the postelcodecvalue property.
		 * 
		 */
		public void setPostelcodecvalue(String value) {
			this.postelcodecvalue = value;
		}

		/**
		 * Gets the value of the ordercommvalue property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getOrdercommvalue() {
			return ordercommvalue;
		}

		/**
		 * Sets the value of the ordercommvalue property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setOrdercommvalue(String value) {
			this.ordercommvalue = value;
		}

	}

}
